---
- name: AWS - Create OpenVPN
  hosts: localhost
  vars_files:
    - "../../vars/{{ ENV }}-aws_vars.yml" # Replace PROD with Var {{ ENV }}
    - "../../../{{ ENV }}-aws_cred-{{ country }}.yml" # Replace PROD with Var {{ ENV }}
  tasks:
    - name: AWS - Get Subnet-id
      amazon.aws.ec2_vpc_subnet_info:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": DMZ-Public
      register: subnet_openvpn

    - name: AWS - Get VPC
      amazon.aws.ec2_vpc_net_info:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ aws_vpc_name }}"
      register: vpc

    - name: AWS - Get SecurityGroups-id
      amazon.aws.ec2_security_group_info:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        filters:
          group-name: DMZ-OpenVPN
      register: sg_openvpn

    - name: AWS - get Internet Gateway-id
      amazon.aws.ec2_vpc_igw_info:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "InternetGateway-OpenVPN"
      register: igw

    - name: AWS - Create Keys-pair
      amazon.aws.ec2_key:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        name: user-key
        state: present
        key_material: 'ssh-rsa <KEY>'

    - name: Create OpenVPN
      amazon.aws.ec2_instance:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ subnet_openvpn.subnets[0].id }}"
        security_group: "{{ sg_openvpn.security_groups[0].group_id }}"
        name: "openvpn"
        key_name: "user-key"
        instance_type: c5a.xlarge
        image_id: ami-0c7217cdde317cfec
        exact_count: 1
        network:
          assign_public_ip: false
        state: present
        tags:
          Environment: PROD
      register: ec2

    - name: Asociate eip
      amazon.aws.ec2_eip:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        device_id: "{{ item }}"
      with_items: "{{ ec2.instance_ids }}"

    - name: AWS - get gateway route table
      amazon.aws.ec2_vpc_route_table_info:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": route-internet

    - name: AWS - Create gateway route table
      amazon.aws.ec2_vpc_route_table:
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_access_key }}"
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc.vpcs[0].id }}"
        state: present
        subnets:
          - "{{ subnet_openvpn.subnets[0].id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.internet_gateways[0].internet_gateway_id }}"
          - dest: 10.0.0.0/16
            instance_id: "{{ ec2.instance_ids[0] }}"
        tags:
          Name: "route-internet"
        gateway_id: "{{ igw.internet_gateways[0].internet_gateway_id }}"
      register: gateway_route_table
